import 'package:finance_buddy_app/core/enums.dart';

/// Comprehensive keyword → category mapping.
/// Lookup is case-insensitive substring match.
class CategoryKeywords {
  CategoryKeywords._();

  static const Map<String, TransactionCategory> map = {
    // ── Food & Drink ──────────────────────────────────
    'paneer': TransactionCategory.foodAndDrink,
    'pizza': TransactionCategory.foodAndDrink,
    'burger': TransactionCategory.foodAndDrink,
    'coffee': TransactionCategory.foodAndDrink,
    'starbucks': TransactionCategory.foodAndDrink,
    'zomato': TransactionCategory.foodAndDrink,
    'swiggy': TransactionCategory.foodAndDrink,
    'restaurant': TransactionCategory.foodAndDrink,
    'lunch': TransactionCategory.foodAndDrink,
    'dinner': TransactionCategory.foodAndDrink,
    'breakfast': TransactionCategory.foodAndDrink,
    'brunch': TransactionCategory.foodAndDrink,
    'groceries': TransactionCategory.foodAndDrink,
    'grocery': TransactionCategory.foodAndDrink,
    'food': TransactionCategory.foodAndDrink,
    'meal': TransactionCategory.foodAndDrink,
    'snack': TransactionCategory.foodAndDrink,
    'chai': TransactionCategory.foodAndDrink,
    'tea': TransactionCategory.foodAndDrink,
    'milk': TransactionCategory.foodAndDrink,
    'bread': TransactionCategory.foodAndDrink,
    'rice': TransactionCategory.foodAndDrink,
    'chicken': TransactionCategory.foodAndDrink,
    'mutton': TransactionCategory.foodAndDrink,
    'fish': TransactionCategory.foodAndDrink,
    'egg': TransactionCategory.foodAndDrink,
    'biryani': TransactionCategory.foodAndDrink,
    'dosa': TransactionCategory.foodAndDrink,
    'idli': TransactionCategory.foodAndDrink,
    'roti': TransactionCategory.foodAndDrink,
    'naan': TransactionCategory.foodAndDrink,
    'dal': TransactionCategory.foodAndDrink,
    'curry': TransactionCategory.foodAndDrink,
    'thali': TransactionCategory.foodAndDrink,
    'samosa': TransactionCategory.foodAndDrink,
    'chaat': TransactionCategory.foodAndDrink,
    'pav bhaji': TransactionCategory.foodAndDrink,
    'mcdonalds': TransactionCategory.foodAndDrink,
    'mcdonald': TransactionCategory.foodAndDrink,
    'kfc': TransactionCategory.foodAndDrink,
    'dominos': TransactionCategory.foodAndDrink,
    'domino': TransactionCategory.foodAndDrink,
    'subway': TransactionCategory.foodAndDrink,
    'blinkit': TransactionCategory.foodAndDrink,
    'bigbasket': TransactionCategory.foodAndDrink,
    'instamart': TransactionCategory.foodAndDrink,
    'zepto': TransactionCategory.foodAndDrink,
    'dunzo': TransactionCategory.foodAndDrink,
    'vegetables': TransactionCategory.foodAndDrink,
    'veggies': TransactionCategory.foodAndDrink,
    'fruits': TransactionCategory.foodAndDrink,
    'fruit': TransactionCategory.foodAndDrink,
    'juice': TransactionCategory.foodAndDrink,
    'smoothie': TransactionCategory.foodAndDrink,
    'ice cream': TransactionCategory.foodAndDrink,
    'icecream': TransactionCategory.foodAndDrink,
    'cake': TransactionCategory.foodAndDrink,
    'bakery': TransactionCategory.foodAndDrink,
    'sweet': TransactionCategory.foodAndDrink,
    'chocolate': TransactionCategory.foodAndDrink,
    'beer': TransactionCategory.foodAndDrink,
    'wine': TransactionCategory.foodAndDrink,
    'alcohol': TransactionCategory.foodAndDrink,
    'liquor': TransactionCategory.foodAndDrink,
    'bar': TransactionCategory.foodAndDrink,
    'pub': TransactionCategory.foodAndDrink,
    'cafe': TransactionCategory.foodAndDrink,
    'canteen': TransactionCategory.foodAndDrink,
    'mess': TransactionCategory.foodAndDrink,
    'tiffin': TransactionCategory.foodAndDrink,
    'dhaba': TransactionCategory.foodAndDrink,
    'haldiram': TransactionCategory.foodAndDrink,
    'momo': TransactionCategory.foodAndDrink,
    'noodles': TransactionCategory.foodAndDrink,
    'pasta': TransactionCategory.foodAndDrink,
    'sushi': TransactionCategory.foodAndDrink,
    'salad': TransactionCategory.foodAndDrink,
    'sandwich': TransactionCategory.foodAndDrink,
    'wrap': TransactionCategory.foodAndDrink,
    'falooda': TransactionCategory.foodAndDrink,
    'lassi': TransactionCategory.foodAndDrink,
    'coke': TransactionCategory.foodAndDrink,
    'pepsi': TransactionCategory.foodAndDrink,
    'soda': TransactionCategory.foodAndDrink,
    'chips': TransactionCategory.foodAndDrink,
    'biscuit': TransactionCategory.foodAndDrink,
    'maggi': TransactionCategory.foodAndDrink,
    'uber eats': TransactionCategory.foodAndDrink,
    'doordash': TransactionCategory.foodAndDrink,
    'grubhub': TransactionCategory.foodAndDrink,
    'chipotle': TransactionCategory.foodAndDrink,
    'wendys': TransactionCategory.foodAndDrink,
    'taco bell': TransactionCategory.foodAndDrink,
    'popeyes': TransactionCategory.foodAndDrink,
    'chick-fil-a': TransactionCategory.foodAndDrink,
    'panner': TransactionCategory.foodAndDrink,

    // ── Transport ─────────────────────────────────────
    'uber': TransactionCategory.transport,
    'ola': TransactionCategory.transport,
    'lyft': TransactionCategory.transport,
    'rapido': TransactionCategory.transport,
    'taxi': TransactionCategory.transport,
    'cab': TransactionCategory.transport,
    'petrol': TransactionCategory.transport,
    'diesel': TransactionCategory.transport,
    'fuel': TransactionCategory.transport,
    'gas station': TransactionCategory.transport,
    'metro': TransactionCategory.transport,
    'bus': TransactionCategory.transport,
    'train': TransactionCategory.transport,
    'auto': TransactionCategory.transport,
    'rickshaw': TransactionCategory.transport,
    'parking': TransactionCategory.transport,
    'toll': TransactionCategory.transport,
    'fastag': TransactionCategory.transport,
    'car wash': TransactionCategory.transport,
    'car service': TransactionCategory.transport,
    'mechanic': TransactionCategory.transport,
    'tyre': TransactionCategory.transport,
    'tire': TransactionCategory.transport,
    'servicing': TransactionCategory.transport,
    'ev charging': TransactionCategory.transport,
    'charging station': TransactionCategory.transport,

    // ── Shopping ──────────────────────────────────────
    'amazon': TransactionCategory.shopping,
    'flipkart': TransactionCategory.shopping,
    'myntra': TransactionCategory.shopping,
    'ajio': TransactionCategory.shopping,
    'meesho': TransactionCategory.shopping,
    'nykaa': TransactionCategory.shopping,
    'clothes': TransactionCategory.shopping,
    'clothing': TransactionCategory.shopping,
    'shoes': TransactionCategory.shopping,
    'sneakers': TransactionCategory.shopping,
    'mall': TransactionCategory.shopping,
    'shopping': TransactionCategory.shopping,
    'electronics': TransactionCategory.shopping,
    'laptop': TransactionCategory.shopping,
    'headphones': TransactionCategory.shopping,
    'furniture': TransactionCategory.shopping,
    'ikea': TransactionCategory.shopping,
    'gift': TransactionCategory.shopping,
    'present': TransactionCategory.shopping,
    'jewellery': TransactionCategory.shopping,
    'jewelry': TransactionCategory.shopping,
    'watch': TransactionCategory.shopping,
    'bag': TransactionCategory.shopping,
    'purse': TransactionCategory.shopping,
    'wallet': TransactionCategory.shopping,
    'target': TransactionCategory.shopping,
    'walmart': TransactionCategory.shopping,
    'costco': TransactionCategory.shopping,
    'best buy': TransactionCategory.shopping,
    'apple store': TransactionCategory.shopping,
    'zara': TransactionCategory.shopping,
    'h&m': TransactionCategory.shopping,
    'uniqlo': TransactionCategory.shopping,
    'nike': TransactionCategory.shopping,
    'adidas': TransactionCategory.shopping,
    'decathlon': TransactionCategory.shopping,
    'croma': TransactionCategory.shopping,
    'reliance digital': TransactionCategory.shopping,

    // ── Bills & Utilities ─────────────────────────────
    'electricity': TransactionCategory.billsAndUtilities,
    'electric bill': TransactionCategory.billsAndUtilities,
    'power bill': TransactionCategory.billsAndUtilities,
    'wifi': TransactionCategory.billsAndUtilities,
    'internet': TransactionCategory.billsAndUtilities,
    'broadband': TransactionCategory.billsAndUtilities,
    'jio': TransactionCategory.billsAndUtilities,
    'airtel': TransactionCategory.billsAndUtilities,
    'vodafone': TransactionCategory.billsAndUtilities,
    'vi': TransactionCategory.billsAndUtilities,
    'bsnl': TransactionCategory.billsAndUtilities,
    'rent': TransactionCategory.billsAndUtilities,
    'mortgage': TransactionCategory.billsAndUtilities,
    'water bill': TransactionCategory.billsAndUtilities,
    'gas bill': TransactionCategory.billsAndUtilities,
    'insurance': TransactionCategory.billsAndUtilities,
    'emi': TransactionCategory.billsAndUtilities,
    'loan': TransactionCategory.billsAndUtilities,
    'credit card bill': TransactionCategory.billsAndUtilities,
    'phone bill': TransactionCategory.billsAndUtilities,
    'recharge': TransactionCategory.billsAndUtilities,
    'mobile recharge': TransactionCategory.billsAndUtilities,
    'dth': TransactionCategory.billsAndUtilities,
    'tata sky': TransactionCategory.billsAndUtilities,
    'maintenance': TransactionCategory.billsAndUtilities,
    'society': TransactionCategory.billsAndUtilities,
    'property tax': TransactionCategory.billsAndUtilities,
    'utility': TransactionCategory.billsAndUtilities,

    // ── Health & Wellness ─────────────────────────────
    'doctor': TransactionCategory.healthAndWellness,
    'hospital': TransactionCategory.healthAndWellness,
    'clinic': TransactionCategory.healthAndWellness,
    'medicine': TransactionCategory.healthAndWellness,
    'pharmacy': TransactionCategory.healthAndWellness,
    'medical': TransactionCategory.healthAndWellness,
    'gym': TransactionCategory.healthAndWellness,
    'fitness': TransactionCategory.healthAndWellness,
    'yoga': TransactionCategory.healthAndWellness,
    'workout': TransactionCategory.healthAndWellness,
    'therapy': TransactionCategory.healthAndWellness,
    'therapist': TransactionCategory.healthAndWellness,
    'dentist': TransactionCategory.healthAndWellness,
    'dental': TransactionCategory.healthAndWellness,
    'eye doctor': TransactionCategory.healthAndWellness,
    'optician': TransactionCategory.healthAndWellness,
    'lab test': TransactionCategory.healthAndWellness,
    'blood test': TransactionCategory.healthAndWellness,
    'x-ray': TransactionCategory.healthAndWellness,
    'scan': TransactionCategory.healthAndWellness,
    'apollo': TransactionCategory.healthAndWellness,
    'medplus': TransactionCategory.healthAndWellness,
    'netmeds': TransactionCategory.healthAndWellness,
    'pharmeasy': TransactionCategory.healthAndWellness,
    'practo': TransactionCategory.healthAndWellness,
    'supplement': TransactionCategory.healthAndWellness,
    'vitamin': TransactionCategory.healthAndWellness,
    'protein': TransactionCategory.healthAndWellness,
    'wellness': TransactionCategory.healthAndWellness,
    'health': TransactionCategory.healthAndWellness,
    'cult fit': TransactionCategory.healthAndWellness,
    'crossfit': TransactionCategory.healthAndWellness,

    // ── Entertainment ─────────────────────────────────
    'movie': TransactionCategory.entertainment,
    'movies': TransactionCategory.entertainment,
    'cinema': TransactionCategory.entertainment,
    'pvr': TransactionCategory.entertainment,
    'inox': TransactionCategory.entertainment,
    'netflix': TransactionCategory.entertainment,
    'hotstar': TransactionCategory.entertainment,
    'disney': TransactionCategory.entertainment,
    'prime video': TransactionCategory.entertainment,
    'spotify': TransactionCategory.entertainment,
    'apple music': TransactionCategory.entertainment,
    'youtube premium': TransactionCategory.entertainment,
    'youtube': TransactionCategory.entertainment,
    'gaming': TransactionCategory.entertainment,
    'game': TransactionCategory.entertainment,
    'playstation': TransactionCategory.entertainment,
    'xbox': TransactionCategory.entertainment,
    'steam': TransactionCategory.entertainment,
    'concert': TransactionCategory.entertainment,
    'event': TransactionCategory.entertainment,
    'ticket': TransactionCategory.entertainment,
    'bookmyshow': TransactionCategory.entertainment,
    'amusement': TransactionCategory.entertainment,
    'theme park': TransactionCategory.entertainment,
    'bowling': TransactionCategory.entertainment,
    'karaoke': TransactionCategory.entertainment,
    'streaming': TransactionCategory.entertainment,
    'hbo': TransactionCategory.entertainment,
    'hulu': TransactionCategory.entertainment,
    'jio cinema': TransactionCategory.entertainment,
    'zee5': TransactionCategory.entertainment,
    'sonyliv': TransactionCategory.entertainment,

    // ── Personal Care ─────────────────────────────────
    'haircut': TransactionCategory.personalCare,
    'salon': TransactionCategory.personalCare,
    'spa': TransactionCategory.personalCare,
    'massage': TransactionCategory.personalCare,
    'facial': TransactionCategory.personalCare,
    'waxing': TransactionCategory.personalCare,
    'manicure': TransactionCategory.personalCare,
    'pedicure': TransactionCategory.personalCare,
    'skincare': TransactionCategory.personalCare,
    'makeup': TransactionCategory.personalCare,
    'cosmetics': TransactionCategory.personalCare,
    'perfume': TransactionCategory.personalCare,
    'grooming': TransactionCategory.personalCare,
    'barber': TransactionCategory.personalCare,
    'shampoo': TransactionCategory.personalCare,
    'soap': TransactionCategory.personalCare,
    'lotion': TransactionCategory.personalCare,
    'sunscreen': TransactionCategory.personalCare,
    'beauty': TransactionCategory.personalCare,
    'parlour': TransactionCategory.personalCare,
    'parlor': TransactionCategory.personalCare,
    'dermatologist': TransactionCategory.personalCare,
    'laundry': TransactionCategory.personalCare,
    'dry clean': TransactionCategory.personalCare,
    'tailor': TransactionCategory.personalCare,

    // ── Education ─────────────────────────────────────
    'tuition': TransactionCategory.education,
    'school': TransactionCategory.education,
    'college': TransactionCategory.education,
    'university': TransactionCategory.education,
    'course': TransactionCategory.education,
    'udemy': TransactionCategory.education,
    'coursera': TransactionCategory.education,
    'skillshare': TransactionCategory.education,
    'masterclass': TransactionCategory.education,
    'books': TransactionCategory.education,
    'book': TransactionCategory.education,
    'textbook': TransactionCategory.education,
    'stationery': TransactionCategory.education,
    'exam': TransactionCategory.education,
    'coaching': TransactionCategory.education,
    'tutorial': TransactionCategory.education,
    'class': TransactionCategory.education,
    'workshop': TransactionCategory.education,
    'seminar': TransactionCategory.education,
    'certification': TransactionCategory.education,
    'library': TransactionCategory.education,
    'notebook': TransactionCategory.education,
    'pen': TransactionCategory.education,
    'byju': TransactionCategory.education,
    'unacademy': TransactionCategory.education,
    'linkedin learning': TransactionCategory.education,
    'chatgpt': TransactionCategory.education,
    'claude': TransactionCategory.education,
    'notion': TransactionCategory.education,
    'canva': TransactionCategory.education,

    // ── Travel ────────────────────────────────────────
    'flight': TransactionCategory.travel,
    'airline': TransactionCategory.travel,
    'indigo': TransactionCategory.travel,
    'air india': TransactionCategory.travel,
    'spicejet': TransactionCategory.travel,
    'vistara': TransactionCategory.travel,
    'hotel': TransactionCategory.travel,
    'hostel': TransactionCategory.travel,
    'airbnb': TransactionCategory.travel,
    'oyo': TransactionCategory.travel,
    'makemytrip': TransactionCategory.travel,
    'goibibo': TransactionCategory.travel,
    'booking.com': TransactionCategory.travel,
    'agoda': TransactionCategory.travel,
    'resort': TransactionCategory.travel,
    'vacation': TransactionCategory.travel,
    'holiday': TransactionCategory.travel,
    'trip': TransactionCategory.travel,
    'travel': TransactionCategory.travel,
    'luggage': TransactionCategory.travel,
    'suitcase': TransactionCategory.travel,
    'passport': TransactionCategory.travel,
    'visa': TransactionCategory.travel,
    'tourism': TransactionCategory.travel,
    'cleartrip': TransactionCategory.travel,
    'ixigo': TransactionCategory.travel,
    'irctc': TransactionCategory.travel,
    'redbus': TransactionCategory.travel,

    // ── Other ─────────────────────────────────────────
    'donation': TransactionCategory.other,
    'charity': TransactionCategory.other,
    'tip': TransactionCategory.other,
    'atm': TransactionCategory.other,
    'cash': TransactionCategory.other,
    'transfer': TransactionCategory.other,
    'pet': TransactionCategory.other,
    'vet': TransactionCategory.other,
    'dog': TransactionCategory.other,
    'cat': TransactionCategory.other,
  };

  /// Find the best category for the given text.
  /// Uses substring matching — "paneer tikka" matches "paneer" → Food & Drink.
  static TransactionCategory? match(String text) {
    final input = text.trim().toLowerCase();
    if (input.isEmpty) return null;

    // 1. Exact match
    final exact = map[input];
    if (exact != null) return exact;

    // 2. Longest substring match (prefer longer keywords)
    TransactionCategory? best;
    int bestLen = 0;
    for (final entry in map.entries) {
      if (input.contains(entry.key) && entry.key.length > bestLen) {
        best = entry.value;
        bestLen = entry.key.length;
      }
    }
    if (best != null) return best;

    // 3. Check if any keyword contains the input (handles partial typing)
    for (final entry in map.entries) {
      if (entry.key.contains(input) && input.length >= 3) {
        return entry.value;
      }
    }

    return null;
  }
}
